PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name
WHERE {
    ?subject a schema:InfectiousDisease .
    ?subject schema:additionalProperty ?additionalproperty .
    ?subject schema:name ?name .

    ?subject schema:spatialCoverage ?spatialcoverage .
    ?spatialcoverage schema:name ?spatial_name .
    FILTER (REGEX(?spatial_name, "China"))

}
GROUP BY ?name
