PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?label

WHERE {
    VALUES ?type { schema:InfectiousAgentClass schema:Place schema:Taxon}
        ?subject a ?type .
        ?subject schema:name ?label .

 FILTER(
                 isIRI(?subject) &&
    !isBlank(?subject)
    )
}
